conf/urls.py
from django.conf.urls import patterns, include, url

from ikwen.core.views import Offline, DashboardBase
from ikwen.flatpages.views import FlatPageView
from marketplace.views import ShowProductList

urlpatterns = patterns(
    '',
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^offline.html$', Offline.as_view(), name='offline'),
    url(r'^billing/', include('ikwen.billing.urls', namespace='billing')),
    url(r'^theming/', include('ikwen.theming.urls', namespace='theming')),
    url(r'^page/(?P<url>[-\w]+)/$', FlatPageView.as_view(), name='flatpage'),
    url(r'^echo/', include('echo.urls', namespace='echo')),
    url(r'^ikwen/cashout/', include('ikwen.cashout.urls', namespace='cashout')),
    url(r'^ikwen/', include('ikwen.core.urls', namespace='ikwen')),

    url(r'^gorilla/dashboard$', DashboardBase.as_view(), name='admin_home'),
    url(r'^gorilla/dashboard$', DashboardBase.as_view(), name='dashboard'),
    url(r'^$', ShowProductList.as_view(), name='home'),
    url(r'^', include('marketplace.urls', namespace='marketplace')),
)

marketplace/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import permission_required

from marketplace.views import ShowProductList, ProductDetail, ProductList, ChangeProduct, set_momo_payment, \
    confirm_payment

urlpatterns = patterns(
    '',
    url(r'^laakam/products/$', permission_required('accesscontrol.sudo')(ProductList.as_view()), name='product_list'),
    url(r'^laakam/product$', permission_required('accesscontrol.sudo')(ChangeProduct.as_view()), name='change_product'),
    url(r'^laakam/product/(?P<object_id>[-\w]+)$', permission_required('accesscontrol.sudo')(ChangeProduct.as_view()), name='change_product'),

    url(r'^$', ShowProductList.as_view(), name='home'),

    url(r'^set_momo_payment$', set_momo_payment),
    url(r'^confirm_payment/(?P<tx_id>[-\w]+)/(?P<signature>[-\w]+)$', confirm_payment, name='confirm_payment'),

    url(r'^(?P<slug>[-\w]+)$', ProductDetail.as_view(), name='product_detail'),
    url(r'^(?P<slug>[-\w]+)/(?P<payment_id>[-\w]+)$', ProductDetail.as_view(), name='product_detail'),
)

templates/core/app_base_admin.html
{% extends "core/base_admin.html" %}
{% load i18n static auth_tokens %}
{% block app_admin_nav %}
    <ul class="nav nav-pills nav-stacked">
        <li role="presentation" class="dashboard">
            <a href="{% url 'admin_home' %}">{% trans "Dashboard" %}</a>
        </li>
    </ul>
    <ul class="nav nav-pills nav-stacked">
        <li role="presentation" class="products">
            {% url 'marketplace:product_list' as product_list_url %}
            <a href="{{ product_list_url }}">{% trans "Products" %}</a>
        </li>
    </ul>
    <ul class="nav nav-pills nav-stacked">
        <li role="presentation" class="subscriptions">
            {% url 'billing:subscription_list' as subscription_list_url %}
            <a href="{{ subscription_list_url }}">{% trans "Subscriptions" %}</a>
        </li>
    </ul>
{% endblock %}